# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/oas-explorer',
                'doc_host': 'https://AckerDWM.github.io',
                'git_url': 'https://github.com/AckerDWM/oas-explorer',
                'lib_path': 'oas_explorer'},
  'syms': {'oas_explorer.core': {'oas_explorer.core.foo': ('core.html#foo', 'oas_explorer/core.py')}}}